spring:
  datasource:
    username: root
    password: admin123.
    url: jdbc:mysql://localhost:3306/experiment?serverTimezone=GMT%2B8

server:
  port: 8080

logging:
  level:
    com.sx: debug

ep:
  cfg:
    cors-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
  upload:
    base-path: D:/experiment/
    upload-path: upload/
    image-path: img/
    video-path: video/
